export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAILURE = 'MOVIE_LIST_FAILURE';

export const MOVIE_DETAIL_REQUEST = 'MOVIE_DETAIL_REQUEST';
export const MOVIE_DETAIL_SUCCESS = 'MOVIE_DETAIL_SUCCESS';
export const MOVIE_DETAIL_FAILURE = 'MOVIE_DETAIL_FAILURE';